{% set name = "radical.utils" %}
{% set version = "1.5.3" %}
{% set sha256 = "b87bb764822d9ee5dc363a3e07320c1e42eb5c3a22e93e034e33f8dd3cae0f39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py2k or win]


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - wheel
    - pyzmq
    - regex
    - future
    - msgpack
    - pymongo
    - colorama
    - netifaces
    - setproctitle
    - radical.gtod
    

test:
  imports:
    - radical.utils

about:
  home: https://github.com/radical-cybertools/radical.utils
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Shared code and tools for various RADICAL Projects (http://radical.rutgers.edu/)
  description: |
    This Python package contains shared code and tools for various Radical Group projects.
  dev_url: https://github.com/radical-cybertools/radical.utils

extra:
  recipe-maintainers:
    - andre-merzky
    - iparask
